make.title(Info.name + " on Atlas");
make.setTarget(document.body);
make.h1(Info.name, { id: "atlas-name"});
make.h3("By " + Info.creator, { id: "atlas-creator"});
make.p("Released on " + Info.releaseDate, { id: "atlas-releaseDate"});
make.iframe("", { id: "atlas-preview", src: Info.previewLink, styles: "height:400px; width:500px"});
make.div("", { id: "div-container", styles:" display: flex; justify-content: space-between; width: 550px;" });
make.setTarget($("div-container"));
make.button("Fullscreen", { id: "atlas-fullscreen"});
make.button("Github Page", { id: "atlas-github" });
make.button("View License", { id: "atlas-License" });
make.button("Go to Website", { id: "atlas-website" });
make.setTarget(document.body);
$("atlas-fullscreen").addEventListener("click", () => window.open(Info.previewLink));
$("atlas-github").addEventListener("click", () => window.open(Info.Github);
$("atlas-License").addEventListener("click", () => window.open(Info.license));
$("atlas-website").addEventListener("click", () => window.open(Info.website));
